name: CI

on:
  pull_request:
    branches: [ "main" ]

  # Allow manual execution from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.9.0"

      - name: Check code formatting
        run: terraform fmt -recursive

      - name: Initialise Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd environments/prod
          terraform init

      - name: Validate configuration
        run: terraform validate

      - name: Verify execution viability
        run: |
          terraform plan
